### ISSUE TITLE
Update manifest private data

### ISSUE THREAD

**Issue by jdhitsolutions** [richardhicks/aovpntools#1]
Your module manifest should include private data with links to your license and this repo as the Project URI. When people search for your module, having the project link is helpful so they can review it before deciding to install it. If it helps, take a look at [one of my module manifests](https://github.com/jdhitsolutions/PSWorkItem/blob/main/PSWorkItem.psd1).

**Comment by richardhicks** [comment]
Thanks for bringing that to my attention. I've updated the manifest to include links to those resources, as suggested.
