### ISSUE TITLE
Get-PublicIPAddress should write an object for detail

### ISSUE THREAD

**Issue by jdhitsolutions** [richardhicks/aovpntools#2]
I like the `-Detailed` option in `Get-PublicIPAddress`. But instead of writing three strings, you should write an object to the pipeline. 

```powershell
If ($Detailed) {
     [PSCustomObject]@{
        City = $Content.City
        Country = $Content.Country
        Hostname = $content.HostName
     }
}
```

But since you are getting more data, why not return more of it, like TimeZone and Region? You have no way of knowing how a user might want to use the output so make it as rich as possible.  Just make sure your property names are formatted like `ZipCode` and not  `zip_code`.

**Comment by richardhicks** [comment]
Excellent idea. Function updated to output as object and include additional detail with the -Detailed switch.

**Comment by richardhicks** [comment]
Updated.
