### ISSUE TITLE
Get-TLSCerticate Output

### ISSUE THREAD

**Issue by jdhitsolutions** [richardhicks/aovpntools#3]
In `Get-TLSCertificate` you have this as output:

```powershell
        Write-Output ''
        Write-Output $Certificate.ToString()
```

The end result is that the command is writing an array to the pipeline. The first is an empty string, and then the certificate is a string.  If someone is counting, it makes it look like there are 2 certificates.

I know you have an option to save the certificate to a file, but I think you should write the native certificate object to the pipeline. Again, you don't know if someone might want to save it as an object and work with it. Don't think "text". You could always add a parameter set with a `ToString` parameter.

**Comment by richardhicks** [comment]
You're right, that might appear to someone else as two certificates. This was a blank string to make the output formatting more pleasant, but it is unimportant. I've removed it.
