### ISSUE TITLE
Checking for modules

### ISSUE THREAD

**Issue by jdhitsolutions** [richardhicks/aovpntools#5]
You have code like this to test if a module is installed:
```powershell
Write-Verbose 'Checking for the Active Directory PowerShell module...'
$AdModule = Get-Module -Name ActiveDirectory
```

Your code only checks to see if the module is loaded in your current session.  I suspect you want to verify it is installed. For that, you need to modify your `Get-Module` command.

```powershell
Get-Module -name ActiveDirectory -listAvailable
```

The better approach would be to modify the manifest and make the module a dependency.

```powershell
PrivateData @{
  ...
  ExternalModuleDependencies = @('ActiveDirectory', 'DNSClient')
}
```

If you define the requirement in the manifest, you shouldn't need any validation code in your functions.

**Comment by richardhicks** [comment]
I'm not sure I understand. These modules will only be available if the role/feature is installed. How does adding them to the external module dependencies help? Does that assume the role is installed in the first place? Also, if they are included in the external dependencies, are they all loaded when my module is installed? Thanks!

**Comment by jdhitsolutions** [comment]
My code sample is an example, not necessarily based on your module. But you do have commands in your module that require the ADModule. Instead of testing for the AD module in the function, declaring it as a dependency means that when the module is loaded, it will also load the AD module and throw an error if it isn't found. You need to document in the repo's README what your external dependencies are, and I think you should define them in the manifest. That's the purpose of the manifest. It is up to the user to ensure they meet the requirements to use your module.

There is another section of the manifest for `RequiredModules`. Anything you put here is also treated as a dependency, but if the module isn't found, PowerShell will try to install it from the PowerShell Gallery. Since the AD module is not in the PowerShell Gallery, you would __not__ include it here.

**Comment by richardhicks** [comment]
Thanks for the insight, Jeff. As this is the only function in the module that requires the ActiveDirectory module to be installed, I'm hesitant to make it a requirement for the entire module. With that, I've decided to remove this function from the module for now. I will, however, update the manifest to require the RemoteAccess module as it is used extensively throughout this module.
