### ISSUE TITLE
What is the target for this module?

### ISSUE THREAD

**Issue by jdhitsolutions** [richardhicks/aovpntools#6]
I am curious about the overall design of this module. Some of the commands look like they should be run on a user's desktop, and some should be run on a server. This would mean installing this module on the server and then opening an interactive session to run the command.

As you work on this module, I'd suggest taking the approach that the module would be installed on the admin desktop. Everything runs from there. The commands that need to run on a remote server like the install X commands, should use remoting so that the admin can deploy from their desktop. They should not be forced to RDP or open and interactive session ON the server.

**Comment by richardhicks** [comment]
This module is a collection of miscellaneous tools I have created to perform configuration, optimization, security hardening, and troubleshooting related to Microsoft Always On VPN. Indeed, most of the tools would be run on the server during initial configuration or maintenance, but some are for client-side configuration and troubleshooting. In the future, I'll consider redesigning the toolset so most tools, especially configuration tools, can be run remotely from an admin workstation.
