### ISSUE TITLE
Use Switch statement in place of multiple If/Else statements

### ISSUE THREAD

**Issue by jdhitsolutions** [richardhicks/aovpntools#7]
I noticed in `Optimize-VpnServerTlsConfiguration` that you are using multiple IF/Else statements based on the value of the OSVersion. I suggest refactoring to use the `Switch` statement. You can even use regex matching.

```powershell
Switch -regex ($OSVersion) {
 "^6\.*" {
 Write-Verbose 'Detected Windows Server 2012 or 2012R2.'
...
  }
"14393|17134"  {
Write-Verbose 'Detected Windows Server 2016 or SAC release.'
   }
}
```

**Comment by richardhicks** [comment]
You're right; this would be much better using a Switch statement. I think this is one of my earliest scripts in this collection, so using If/Else was the only way I knew how to do this at the time. ;) I will definitely clean this up when time permits. I'll leave this open to remind me to do it, though. :)

**Comment by richardhicks** [comment]
Updated function to use a Switch statement as suggested. Thanks, Jeff!
