### ISSUE TITLE
Optimize-InboxAccountingDatabase missing

### ISSUE THREAD

**Issue by bballpaul4work** [richardhicks/aovpntools#8]
When running Install-VpnServer, we get the error 

> Optimize-InboxAccountingDatabase : The term 'Optimize-InboxAccountingDatabase' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\AOVPNTools\1.8\Functions\Install-VpnServer.ps1:126 char:5

When checking the Functions folder on Github, this file doesn't exist

**Comment by richardhicks** [comment]
I apologize. This function is included in a different module. You'll need to install the InboxAccountingDatabaseModule for this to work.

Install-Module -Name InboxAccountingDatabaseManagement -Force

I will update this function to include the dependency and add some error handling to surface an appropriate error message referencing the additional module requirement.

Thanks!

**Comment by richardhicks** [comment]
Updated function to include the #Requires statement indicating the InboxAccountingDatabaseManagement must be loaded before running this script. The InboxAccountingDatabaseManagement can be installed using the Install-Module InboxAccountingDatabaseManagmenet command.
